# Generated by Django 3.2.7 on 2021-09-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_name', models.CharField(max_length=30)),
                ('stand_user', models.CharField(max_length=30)),
                ('destructive_power_stat', models.CharField(choices=[('A', 'Very Good'), ('B', 'Good'), ('C', 'Average'), ('D', 'Poor'), ('E', 'Very Poor'), ('∅', 'None'), ('∞', 'Infinite'), ('?', 'Unknown')], default='?', max_length=1)),
                ('speed_stat', models.CharField(choices=[('A', 'Very Good'), ('B', 'Good'), ('C', 'Average'), ('D', 'Poor'), ('E', 'Very Poor'), ('∅', 'None'), ('∞', 'Infinite'), ('?', 'Unknown')], default='?', max_length=1)),
                ('range_stat', models.CharField(choices=[('A', 'Very Good'), ('B', 'Good'), ('C', 'Average'), ('D', 'Poor'), ('E', 'Very Poor'), ('∅', 'None'), ('∞', 'Infinite'), ('?', 'Unknown')], default='?', max_length=1)),
                ('stamina_stat', models.CharField(choices=[('A', 'Very Good'), ('B', 'Good'), ('C', 'Average'), ('D', 'Poor'), ('E', 'Very Poor'), ('∅', 'None'), ('∞', 'Infinite'), ('?', 'Unknown')], default='?', max_length=1)),
                ('precision_stat', models.CharField(choices=[('A', 'Very Good'), ('B', 'Good'), ('C', 'Average'), ('D', 'Poor'), ('E', 'Very Poor'), ('∅', 'None'), ('∞', 'Infinite'), ('?', 'Unknown')], default='?', max_length=1)),
                ('development_potential_stat', models.CharField(choices=[('A', 'Very Good'), ('B', 'Good'), ('C', 'Average'), ('D', 'Poor'), ('E', 'Very Poor'), ('∅', 'None'), ('∞', 'Infinite'), ('?', 'Unknown')], default='?', max_length=1)),
            ],
        ),
    ]
